name: desktop-helpers
version: 1
summary: Various technology desktop helpers for snapcraft
description: |
  Those contains helpers for gtk2, gtk3, qt4 and qt5.
  It brings the necessary code for binding and using those
  and other desktop technologies in a relocatable fashion, still
  linking to desktop properties.
  It also brings basics ubuntu dependency packages.
confinement: strict

parts:
  gtk2:
    source: .
    source-subdir: gtk
    plugin: make
    build-packages:
      - libgtk2.0-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libgtk2.0-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk2.0-bin
      - unity-gtk2-module
  gtk3:
    source: .
    source-subdir: gtk
    plugin: make
    build-packages:
      - libgtk-3-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
