name: gtk2-demo
version: "0"
summary: Gtk2 launcher demo
description: This is using the gtk2 demo
confinement: strict

apps:
  gtk2-demo:
    command: gtk-launch gtk-demo
    plugs: [unity7, x11, gsettings, home]
  gsettings:
    command: gtk-launch gsettings
    plugs: [x11, gsettings, home]

parts:
  gtk2-demo:
    plugin: nil
    stage-packages: [gtk2.0-examples, libglib2.0-bin]
  # this is the cloud part
  gtk2-launcher:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    build-packages:
      - libgtk2.0-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libgtk2.0-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk2.0-bin
      - unity-gtk2-module
