name: gtk2-demo
version: "0"
summary: Gtk2 launcher demo
description: This is using the gtk2 demo
confinement: strict

apps:
  gtk2-demo:
    command: gtk-launch gtk-demo
    plugs: [unity7, x11, gsettings, home]
  gsettings:
    command: gtk-launch gsettings
    plugs: [x11, gsettings, home]

parts:
  gtk2-demo:
    plugin: nil
    stage-packages: [gtk2.0-examples, libglib2.0-bin]
    after: [gtk2]
