name: gtk3-demo
version: "0"
summary: Gtk3 launcher demo
description: This is using the gtk3 demo
grade: stable
confinement: strict

apps:
  gtk3-demo:
    command: desktop-launch gtk-demo
    plugs: [unity7, x11, gsettings, home]
  gsettings:
    command: desktop-launch gsettings
    plugs: [x11, gsettings, home]

parts:
  gtk3-demo:
    plugin: nil
    stage-packages: [gtk-3-examples, libglib2.0-bin]
    after: [desktop-gtk3]
