name: gtk3-demo
version: "0"
summary: Gtk3 launcher demo
description: This is using the gtk3 demo
confinement: strict

apps:
  gtk3-demo:
    command: gtk-launch gtk-demo
    plugs: [unity7, x11, gsettings, home]
  gsettings:
    command: gtk-launch gsettings
    plugs: [x11, gsettings, home]

parts:
  gtk3-demo:
    plugin: nil
    stage-packages: [gtk-3-examples, libglib2.0-bin]
    after: [gtk3]
